export const answers = [
	"hi",
	"hey",
	"hello",
	"Hey there",
	"how are you",
	"how are things",
	"what is going on",
	"what is up",
	"happy",
	"good",
	"well",
	"fantastic",
	"cool",
	"bad",
	"bored",
	"tired", "sad",
	"tell me story",
	"tell me joke",
	"thanks",
	"thank you",
	"bye",
	"good bye",
	"goodbye",
	"Hello!",
	"Hi!",
	"Hey!",
	"Hi there!",
	"Fine... how are you?",
	"Pretty well, how are you?",
	"Fantastic, how are you?",
	"Nothing much",
	"Exciting things!",
	"Glad to hear it",
	"Why?",
	"Cheer up buddy",
	"What about?",
	"Once upon a time...",
	"You're welcome",
	"No problem",
	"Goodbye",
	"See you later",
	"Same",
	"Go on...",
	"Try again",
	"I'm listening...",
	"Bro...",
	"OK"
];


// https://dev.to/sylviapap/make-a-simple-chatbot-with-javascript-1gc
